services:

  server:
    build:
      context: ./dockerfiles
      dockerfile: 'node.dockerfile'
    ports:
     - '4040:4040'
    working_dir: /home/node/app
    volumes:
      - ./src:/home/node/app
    environment:
      - NODE_ENV=production
    command: npm start
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  grafana:
    image: grafana/grafana-enterprise
    ports: 
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: always

volumes:
  grafana-storage: {} # Anonymus volume

